ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy/mm/dd hh24:mi:ss';

ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR';

SELECT
    SYSDATE,
    SYSTIMESTAMP,
    CURRENT_DATE,
    CURRENT_TIMESTAMP
FROM
    DUAL;

SHOW PARAMETERS;            // XX